repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        name: Check issue template config
        files: ^\.github/ISSUE_TEMPLATE/config\.yml$
        args: ["--schemafile", "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-issue-config.json"]
      - id: check-jsonschema
        name: Check issue forms
        files: ^\.github/ISSUE_TEMPLATE/(?!config).*\.yml$
        args: ["--schemafile", "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-issue-forms.json"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
