name: ✨ Feature enhancement
description: Propose a new feature or an enhancement to an existing feature.
labels: ["enhancement"]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Please confirm and check all the following options.
      options:
        - label: I added a descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar request and didn't find it.
          required: true
        - label: If there are docs, I have followed them, and I still think this feature is missing
          required: true

  - type: textarea
    attributes:
      label: Describe the proposed behavior
      description: |
        A clear and concise description of what new feature or behavior you would like to see

        You might like to add a demo of how code might look when using the feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example use case
      description: An example use case that would benefit from this feature
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Provide additional context about the use case here.
    validations:
      required: false
