blank_issues_enabled: true
contact_links:
  - name: 💬 Chat with protectors
    url: https://github.com/orgs/protective-emerging-tech/discussions
    about: Chat with other Protective employees that are using GitHub at Protective
